# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: facerec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'facerec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfacerec.proto\x12\x07\x66\x61\x63\x65rec\"u\n\tFrameTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x17\n\x0fis_registration\x18\x03 \x01(\x08\x12\x13\n\x0b\x64\x65tect_mode\x18\x04 \x01(\t\x12\x15\n\rreload_models\x18\x05 \x01(\x08\"\xe9\x01\n\x0fInferenceResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12&\n\ndetections\x18\x02 \x03(\x0b\x32\x12.facerec.Detection\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x17\n\x0fprocess_time_ms\x18\x04 \x01(\x02\x12\x31\n\x10plate_detections\x18\x05 \x03(\x0b\x32\x17.facerec.PlateDetection\x12:\n\x15plate_training_frames\x18\x06 \x03(\x0b\x32\x1b.facerec.PlateTrainingFrame\"H\n\tDetection\x12\x0c\n\x04\x62\x62ox\x18\x01 \x03(\x02\x12\x11\n\tembedding\x18\x02 \x03(\x02\x12\x1a\n\x12restored_face_jpeg\x18\x03 \x01(\x0c\"\xb1\x01\n\x0ePlateDetection\x12\x0c\n\x04\x62\x62ox\x18\x01 \x03(\x02\x12\x14\n\x0cplate_number\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x12\n\nplate_type\x18\x04 \x01(\t\x12\x10\n\x08province\x18\x05 \x01(\t\x12\x10\n\x08raw_text\x18\x06 \x01(\t\x12\x18\n\x10\x63har_labels_json\x18\x07 \x01(\t\x12\x15\n\rsnapshot_jpeg\x18\x08 \x01(\x0c\"y\n\x12PlateTrainingFrame\x12\x11\n\tcrop_jpeg\x18\x01 \x01(\x0c\x12\x18\n\x10\x63har_labels_json\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08raw_text\x18\x04 \x01(\t\x12\x10\n\x08track_id\x18\x05 \x01(\t2Y\n\x14\x46\x61\x63\x65InferenceService\x12\x41\n\rProcessStream\x12\x18.facerec.InferenceResult\x1a\x12.facerec.FrameTask(\x01\x30\x01\x42\x0bZ\t./facerecb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facerec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./facerec'
  _globals['_FRAMETASK']._serialized_start=26
  _globals['_FRAMETASK']._serialized_end=143
  _globals['_INFERENCERESULT']._serialized_start=146
  _globals['_INFERENCERESULT']._serialized_end=379
  _globals['_DETECTION']._serialized_start=381
  _globals['_DETECTION']._serialized_end=453
  _globals['_PLATEDETECTION']._serialized_start=456
  _globals['_PLATEDETECTION']._serialized_end=633
  _globals['_PLATETRAININGFRAME']._serialized_start=635
  _globals['_PLATETRAININGFRAME']._serialized_end=756
  _globals['_FACEINFERENCESERVICE']._serialized_start=758
  _globals['_FACEINFERENCESERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
