# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import facerec_pb2 as facerec__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in facerec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceInferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessStream = channel.stream_stream(
                '/facerec.FaceInferenceService/ProcessStream',
                request_serializer=facerec__pb2.InferenceResult.SerializeToString,
                response_deserializer=facerec__pb2.FrameTask.FromString,
                _registered_method=True)


class FaceInferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessStream(self, request_iterator, context):
        """Bidirectional stream for both real-time frame processing and face registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessStream,
                    request_deserializer=facerec__pb2.InferenceResult.FromString,
                    response_serializer=facerec__pb2.FrameTask.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facerec.FaceInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('facerec.FaceInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceInferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/facerec.FaceInferenceService/ProcessStream',
            facerec__pb2.InferenceResult.SerializeToString,
            facerec__pb2.FrameTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
