// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: facerec.proto

package facerec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaceInferenceService_ProcessStream_FullMethodName = "/facerec.FaceInferenceService/ProcessStream"
)

// FaceInferenceServiceClient is the client API for FaceInferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceInferenceServiceClient interface {
	// Bidirectional stream for both real-time frame processing and face registration
	ProcessStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferenceResult, FrameTask], error)
}

type faceInferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceInferenceServiceClient(cc grpc.ClientConnInterface) FaceInferenceServiceClient {
	return &faceInferenceServiceClient{cc}
}

func (c *faceInferenceServiceClient) ProcessStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferenceResult, FrameTask], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FaceInferenceService_ServiceDesc.Streams[0], FaceInferenceService_ProcessStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferenceResult, FrameTask]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceInferenceService_ProcessStreamClient = grpc.BidiStreamingClient[InferenceResult, FrameTask]

// FaceInferenceServiceServer is the server API for FaceInferenceService service.
// All implementations must embed UnimplementedFaceInferenceServiceServer
// for forward compatibility.
type FaceInferenceServiceServer interface {
	// Bidirectional stream for both real-time frame processing and face registration
	ProcessStream(grpc.BidiStreamingServer[InferenceResult, FrameTask]) error
	mustEmbedUnimplementedFaceInferenceServiceServer()
}

// UnimplementedFaceInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaceInferenceServiceServer struct{}

func (UnimplementedFaceInferenceServiceServer) ProcessStream(grpc.BidiStreamingServer[InferenceResult, FrameTask]) error {
	return status.Error(codes.Unimplemented, "method ProcessStream not implemented")
}
func (UnimplementedFaceInferenceServiceServer) mustEmbedUnimplementedFaceInferenceServiceServer() {}
func (UnimplementedFaceInferenceServiceServer) testEmbeddedByValue()                              {}

// UnsafeFaceInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceInferenceServiceServer will
// result in compilation errors.
type UnsafeFaceInferenceServiceServer interface {
	mustEmbedUnimplementedFaceInferenceServiceServer()
}

func RegisterFaceInferenceServiceServer(s grpc.ServiceRegistrar, srv FaceInferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedFaceInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaceInferenceService_ServiceDesc, srv)
}

func _FaceInferenceService_ProcessStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FaceInferenceServiceServer).ProcessStream(&grpc.GenericServerStream[InferenceResult, FrameTask]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceInferenceService_ProcessStreamServer = grpc.BidiStreamingServer[InferenceResult, FrameTask]

// FaceInferenceService_ServiceDesc is the grpc.ServiceDesc for FaceInferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceInferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "facerec.FaceInferenceService",
	HandlerType: (*FaceInferenceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessStream",
			Handler:       _FaceInferenceService_ProcessStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "facerec.proto",
}
