// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: facerec.proto

package facerec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ImageData      []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // JPEG bytes
	IsRegistration bool                   `protobuf:"varint,3,opt,name=is_registration,json=isRegistration,proto3" json:"is_registration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FrameTask) Reset() {
	*x = FrameTask{}
	mi := &file_facerec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameTask) ProtoMessage() {}

func (x *FrameTask) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameTask.ProtoReflect.Descriptor instead.
func (*FrameTask) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{0}
}

func (x *FrameTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FrameTask) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *FrameTask) GetIsRegistration() bool {
	if x != nil {
		return x.IsRegistration
	}
	return false
}

type InferenceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Detections    []*Detection           `protobuf:"bytes,2,rep,name=detections,proto3" json:"detections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceResult) Reset() {
	*x = InferenceResult{}
	mi := &file_facerec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResult) ProtoMessage() {}

func (x *InferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResult.ProtoReflect.Descriptor instead.
func (*InferenceResult) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *InferenceResult) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bbox          []float32              `protobuf:"fixed32,1,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`           // [x1, y1, x2, y2]
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // 512-dim embedding
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_facerec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{2}
}

func (x *Detection) GetBbox() []float32 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_facerec_proto protoreflect.FileDescriptor

const file_facerec_proto_rawDesc = "" +
	"\n" +
	"\rfacerec.proto\x12\afacerec\"l\n" +
	"\tFrameTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12'\n" +
	"\x0fis_registration\x18\x03 \x01(\bR\x0eisRegistration\"^\n" +
	"\x0fInferenceResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x122\n" +
	"\n" +
	"detections\x18\x02 \x03(\v2\x12.facerec.DetectionR\n" +
	"detections\"=\n" +
	"\tDetection\x12\x12\n" +
	"\x04bbox\x18\x01 \x03(\x02R\x04bbox\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding2Y\n" +
	"\x14FaceInferenceService\x12A\n" +
	"\rProcessStream\x12\x18.facerec.InferenceResult\x1a\x12.facerec.FrameTask(\x010\x01B\vZ\t./facerecb\x06proto3"

var (
	file_facerec_proto_rawDescOnce sync.Once
	file_facerec_proto_rawDescData []byte
)

func file_facerec_proto_rawDescGZIP() []byte {
	file_facerec_proto_rawDescOnce.Do(func() {
		file_facerec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facerec_proto_rawDesc), len(file_facerec_proto_rawDesc)))
	})
	return file_facerec_proto_rawDescData
}

var file_facerec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_facerec_proto_goTypes = []any{
	(*FrameTask)(nil),       // 0: facerec.FrameTask
	(*InferenceResult)(nil), // 1: facerec.InferenceResult
	(*Detection)(nil),       // 2: facerec.Detection
}
var file_facerec_proto_depIdxs = []int32{
	2, // 0: facerec.InferenceResult.detections:type_name -> facerec.Detection
	1, // 1: facerec.FaceInferenceService.ProcessStream:input_type -> facerec.InferenceResult
	0, // 2: facerec.FaceInferenceService.ProcessStream:output_type -> facerec.FrameTask
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_facerec_proto_init() }
func file_facerec_proto_init() {
	if File_facerec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facerec_proto_rawDesc), len(file_facerec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facerec_proto_goTypes,
		DependencyIndexes: file_facerec_proto_depIdxs,
		MessageInfos:      file_facerec_proto_msgTypes,
	}.Build()
	File_facerec_proto = out.File
	file_facerec_proto_goTypes = nil
	file_facerec_proto_depIdxs = nil
}
