// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: facerec.proto

package facerec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameTask struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ImageData            []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // JPEG bytes
	IsRegistration       bool                   `protobuf:"varint,3,opt,name=is_registration,json=isRegistration,proto3" json:"is_registration,omitempty"`
	DetectMode           string                 `protobuf:"bytes,4,opt,name=detect_mode,json=detectMode,proto3" json:"detect_mode,omitempty"`                                   // "face" | "plate" | "both"  (default: "face")
	ReloadModels         bool                   `protobuf:"varint,5,opt,name=reload_models,json=reloadModels,proto3" json:"reload_models,omitempty"`                            // signal worker to reload models from disk (no image needed)
	StartFinetune        bool                   `protobuf:"varint,6,opt,name=start_finetune,json=startFinetune,proto3" json:"start_finetune,omitempty"`                         // signal worker to start fine-tuning
	FinetuneDatasetS3Key string                 `protobuf:"bytes,7,opt,name=finetune_dataset_s3_key,json=finetuneDatasetS3Key,proto3" json:"finetune_dataset_s3_key,omitempty"` // S3 key of exported dataset zip
	FinetuneEpochs       int32                  `protobuf:"varint,8,opt,name=finetune_epochs,json=finetuneEpochs,proto3" json:"finetune_epochs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FrameTask) Reset() {
	*x = FrameTask{}
	mi := &file_facerec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameTask) ProtoMessage() {}

func (x *FrameTask) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameTask.ProtoReflect.Descriptor instead.
func (*FrameTask) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{0}
}

func (x *FrameTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FrameTask) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *FrameTask) GetIsRegistration() bool {
	if x != nil {
		return x.IsRegistration
	}
	return false
}

func (x *FrameTask) GetDetectMode() string {
	if x != nil {
		return x.DetectMode
	}
	return ""
}

func (x *FrameTask) GetReloadModels() bool {
	if x != nil {
		return x.ReloadModels
	}
	return false
}

func (x *FrameTask) GetStartFinetune() bool {
	if x != nil {
		return x.StartFinetune
	}
	return false
}

func (x *FrameTask) GetFinetuneDatasetS3Key() string {
	if x != nil {
		return x.FinetuneDatasetS3Key
	}
	return ""
}

func (x *FrameTask) GetFinetuneEpochs() int32 {
	if x != nil {
		return x.FinetuneEpochs
	}
	return 0
}

type InferenceResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Detections          []*Detection           `protobuf:"bytes,2,rep,name=detections,proto3" json:"detections,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ProcessTimeMs       float32                `protobuf:"fixed32,4,opt,name=process_time_ms,json=processTimeMs,proto3" json:"process_time_ms,omitempty"`
	PlateDetections     []*PlateDetection      `protobuf:"bytes,5,rep,name=plate_detections,json=plateDetections,proto3" json:"plate_detections,omitempty"`
	PlateTrainingFrames []*PlateTrainingFrame  `protobuf:"bytes,6,rep,name=plate_training_frames,json=plateTrainingFrames,proto3" json:"plate_training_frames,omitempty"`
	FinetuneProgress    *FinetuneProgress      `protobuf:"bytes,7,opt,name=finetune_progress,json=finetuneProgress,proto3" json:"finetune_progress,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InferenceResult) Reset() {
	*x = InferenceResult{}
	mi := &file_facerec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResult) ProtoMessage() {}

func (x *InferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResult.ProtoReflect.Descriptor instead.
func (*InferenceResult) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *InferenceResult) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *InferenceResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InferenceResult) GetProcessTimeMs() float32 {
	if x != nil {
		return x.ProcessTimeMs
	}
	return 0
}

func (x *InferenceResult) GetPlateDetections() []*PlateDetection {
	if x != nil {
		return x.PlateDetections
	}
	return nil
}

func (x *InferenceResult) GetPlateTrainingFrames() []*PlateTrainingFrame {
	if x != nil {
		return x.PlateTrainingFrames
	}
	return nil
}

func (x *InferenceResult) GetFinetuneProgress() *FinetuneProgress {
	if x != nil {
		return x.FinetuneProgress
	}
	return nil
}

type FinetuneProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "epoch" | "done" | "error" | "info"
	Epoch         int32                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Epochs        int32                  `protobuf:"varint,3,opt,name=epochs,proto3" json:"epochs,omitempty"`
	BoxLoss       float32                `protobuf:"fixed32,4,opt,name=box_loss,json=boxLoss,proto3" json:"box_loss,omitempty"`
	ClsLoss       float32                `protobuf:"fixed32,5,opt,name=cls_loss,json=clsLoss,proto3" json:"cls_loss,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinetuneProgress) Reset() {
	*x = FinetuneProgress{}
	mi := &file_facerec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinetuneProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinetuneProgress) ProtoMessage() {}

func (x *FinetuneProgress) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinetuneProgress.ProtoReflect.Descriptor instead.
func (*FinetuneProgress) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{2}
}

func (x *FinetuneProgress) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FinetuneProgress) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *FinetuneProgress) GetEpochs() int32 {
	if x != nil {
		return x.Epochs
	}
	return 0
}

func (x *FinetuneProgress) GetBoxLoss() float32 {
	if x != nil {
		return x.BoxLoss
	}
	return 0
}

func (x *FinetuneProgress) GetClsLoss() float32 {
	if x != nil {
		return x.ClsLoss
	}
	return 0
}

func (x *FinetuneProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FinetuneProgress) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Detection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Bbox             []float32              `protobuf:"fixed32,1,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`                                          // [x1, y1, x2, y2]
	Embedding        []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`                                // 512-dim embedding
	RestoredFaceJpeg []byte                 `protobuf:"bytes,3,opt,name=restored_face_jpeg,json=restoredFaceJpeg,proto3" json:"restored_face_jpeg,omitempty"` // CodeFormer restored face crop (JPEG)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_facerec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{3}
}

func (x *Detection) GetBbox() []float32 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Detection) GetRestoredFaceJpeg() []byte {
	if x != nil {
		return x.RestoredFaceJpeg
	}
	return nil
}

type PlateDetection struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Bbox           []float32              `protobuf:"fixed32,1,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`                         // [x1, y1, x2, y2]
	PlateNumber    string                 `protobuf:"bytes,2,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"` // normalized plate text e.g. "กข 1234"
	Confidence     float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	PlateType      string                 `protobuf:"bytes,4,opt,name=plate_type,json=plateType,proto3" json:"plate_type,omitempty"`                  // "standard" | "commercial" | "unknown"
	Province       string                 `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`                                     // Thai province name if detected
	RawText        string                 `protobuf:"bytes,6,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`                        // raw OCR text before validation
	CharLabelsJson string                 `protobuf:"bytes,7,opt,name=char_labels_json,json=charLabelsJson,proto3" json:"char_labels_json,omitempty"` // JSON: [{class_name,cx,cy,bw,bh,confidence}]
	SnapshotJpeg   []byte                 `protobuf:"bytes,8,opt,name=snapshot_jpeg,json=snapshotJpeg,proto3" json:"snapshot_jpeg,omitempty"`         // deskewed plate crop from best-confidence frame
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlateDetection) Reset() {
	*x = PlateDetection{}
	mi := &file_facerec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateDetection) ProtoMessage() {}

func (x *PlateDetection) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateDetection.ProtoReflect.Descriptor instead.
func (*PlateDetection) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{4}
}

func (x *PlateDetection) GetBbox() []float32 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *PlateDetection) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *PlateDetection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PlateDetection) GetPlateType() string {
	if x != nil {
		return x.PlateType
	}
	return ""
}

func (x *PlateDetection) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *PlateDetection) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *PlateDetection) GetCharLabelsJson() string {
	if x != nil {
		return x.CharLabelsJson
	}
	return ""
}

func (x *PlateDetection) GetSnapshotJpeg() []byte {
	if x != nil {
		return x.SnapshotJpeg
	}
	return nil
}

// A single plate crop frame captured for training / active-learning review.
type PlateTrainingFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CropJpeg       []byte                 `protobuf:"bytes,1,opt,name=crop_jpeg,json=cropJpeg,proto3" json:"crop_jpeg,omitempty"`                     // JPEG of deskewed plate crop
	CharLabelsJson string                 `protobuf:"bytes,2,opt,name=char_labels_json,json=charLabelsJson,proto3" json:"char_labels_json,omitempty"` // JSON: [{class_name,cx,cy,bw,bh,confidence}]
	Confidence     float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RawText        string                 `protobuf:"bytes,4,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	TrackId        string                 `protobuf:"bytes,5,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"` // stable UUID for the PlateTrack that generated this frame
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlateTrainingFrame) Reset() {
	*x = PlateTrainingFrame{}
	mi := &file_facerec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateTrainingFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateTrainingFrame) ProtoMessage() {}

func (x *PlateTrainingFrame) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateTrainingFrame.ProtoReflect.Descriptor instead.
func (*PlateTrainingFrame) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{5}
}

func (x *PlateTrainingFrame) GetCropJpeg() []byte {
	if x != nil {
		return x.CropJpeg
	}
	return nil
}

func (x *PlateTrainingFrame) GetCharLabelsJson() string {
	if x != nil {
		return x.CharLabelsJson
	}
	return ""
}

func (x *PlateTrainingFrame) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PlateTrainingFrame) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *PlateTrainingFrame) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

var File_facerec_proto protoreflect.FileDescriptor

const file_facerec_proto_rawDesc = "" +
	"\n" +
	"\rfacerec.proto\x12\afacerec\"\xb9\x02\n" +
	"\tFrameTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12'\n" +
	"\x0fis_registration\x18\x03 \x01(\bR\x0eisRegistration\x12\x1f\n" +
	"\vdetect_mode\x18\x04 \x01(\tR\n" +
	"detectMode\x12#\n" +
	"\rreload_models\x18\x05 \x01(\bR\freloadModels\x12%\n" +
	"\x0estart_finetune\x18\x06 \x01(\bR\rstartFinetune\x125\n" +
	"\x17finetune_dataset_s3_key\x18\a \x01(\tR\x14finetuneDatasetS3Key\x12'\n" +
	"\x0ffinetune_epochs\x18\b \x01(\x05R\x0efinetuneEpochs\"\x88\x03\n" +
	"\x0fInferenceResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x122\n" +
	"\n" +
	"detections\x18\x02 \x03(\v2\x12.facerec.DetectionR\n" +
	"detections\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12&\n" +
	"\x0fprocess_time_ms\x18\x04 \x01(\x02R\rprocessTimeMs\x12B\n" +
	"\x10plate_detections\x18\x05 \x03(\v2\x17.facerec.PlateDetectionR\x0fplateDetections\x12O\n" +
	"\x15plate_training_frames\x18\x06 \x03(\v2\x1b.facerec.PlateTrainingFrameR\x13plateTrainingFrames\x12F\n" +
	"\x11finetune_progress\x18\a \x01(\v2\x19.facerec.FinetuneProgressR\x10finetuneProgress\"\xbe\x01\n" +
	"\x10FinetuneProgress\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x05R\x05epoch\x12\x16\n" +
	"\x06epochs\x18\x03 \x01(\x05R\x06epochs\x12\x19\n" +
	"\bbox_loss\x18\x04 \x01(\x02R\aboxLoss\x12\x19\n" +
	"\bcls_loss\x18\x05 \x01(\x02R\aclsLoss\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"k\n" +
	"\tDetection\x12\x12\n" +
	"\x04bbox\x18\x01 \x03(\x02R\x04bbox\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12,\n" +
	"\x12restored_face_jpeg\x18\x03 \x01(\fR\x10restoredFaceJpeg\"\x8c\x02\n" +
	"\x0ePlateDetection\x12\x12\n" +
	"\x04bbox\x18\x01 \x03(\x02R\x04bbox\x12!\n" +
	"\fplate_number\x18\x02 \x01(\tR\vplateNumber\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"plate_type\x18\x04 \x01(\tR\tplateType\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x19\n" +
	"\braw_text\x18\x06 \x01(\tR\arawText\x12(\n" +
	"\x10char_labels_json\x18\a \x01(\tR\x0echarLabelsJson\x12#\n" +
	"\rsnapshot_jpeg\x18\b \x01(\fR\fsnapshotJpeg\"\xb1\x01\n" +
	"\x12PlateTrainingFrame\x12\x1b\n" +
	"\tcrop_jpeg\x18\x01 \x01(\fR\bcropJpeg\x12(\n" +
	"\x10char_labels_json\x18\x02 \x01(\tR\x0echarLabelsJson\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x19\n" +
	"\braw_text\x18\x04 \x01(\tR\arawText\x12\x19\n" +
	"\btrack_id\x18\x05 \x01(\tR\atrackId2Y\n" +
	"\x14FaceInferenceService\x12A\n" +
	"\rProcessStream\x12\x18.facerec.InferenceResult\x1a\x12.facerec.FrameTask(\x010\x01B\vZ\t./facerecb\x06proto3"

var (
	file_facerec_proto_rawDescOnce sync.Once
	file_facerec_proto_rawDescData []byte
)

func file_facerec_proto_rawDescGZIP() []byte {
	file_facerec_proto_rawDescOnce.Do(func() {
		file_facerec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facerec_proto_rawDesc), len(file_facerec_proto_rawDesc)))
	})
	return file_facerec_proto_rawDescData
}

var file_facerec_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_facerec_proto_goTypes = []any{
	(*FrameTask)(nil),          // 0: facerec.FrameTask
	(*InferenceResult)(nil),    // 1: facerec.InferenceResult
	(*FinetuneProgress)(nil),   // 2: facerec.FinetuneProgress
	(*Detection)(nil),          // 3: facerec.Detection
	(*PlateDetection)(nil),     // 4: facerec.PlateDetection
	(*PlateTrainingFrame)(nil), // 5: facerec.PlateTrainingFrame
}
var file_facerec_proto_depIdxs = []int32{
	3, // 0: facerec.InferenceResult.detections:type_name -> facerec.Detection
	4, // 1: facerec.InferenceResult.plate_detections:type_name -> facerec.PlateDetection
	5, // 2: facerec.InferenceResult.plate_training_frames:type_name -> facerec.PlateTrainingFrame
	2, // 3: facerec.InferenceResult.finetune_progress:type_name -> facerec.FinetuneProgress
	1, // 4: facerec.FaceInferenceService.ProcessStream:input_type -> facerec.InferenceResult
	0, // 5: facerec.FaceInferenceService.ProcessStream:output_type -> facerec.FrameTask
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_facerec_proto_init() }
func file_facerec_proto_init() {
	if File_facerec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facerec_proto_rawDesc), len(file_facerec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facerec_proto_goTypes,
		DependencyIndexes: file_facerec_proto_depIdxs,
		MessageInfos:      file_facerec_proto_msgTypes,
	}.Build()
	File_facerec_proto = out.File
	file_facerec_proto_goTypes = nil
	file_facerec_proto_depIdxs = nil
}
